---
title: "First Knit"
author: "Janette Quezada"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
What high school did you go to, and where?Did you have trouble with any   
  
### my answer     
  

     I went to Pete knight high school in Palmdale,CA. and yes I did graduate. English was my worst subject compared to Math,I also struggled with math but not as bad as English. I was best at Math with a lot of tutoring I had to work harder than some of my classmates because of my memory.Overall i liked the experience of both regardless of how challenging it was.   


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
I have a hp computer.I believe in a scale on 1 to 10 i am at a 3. My internet is fine at home but i only have access to my hotspot or starbucks internet.

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
   I would like to be called Janette by everyone.My nickname would be JJ if people prefer to call me that its fine.
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
   My goal in life is to become successful in my business, which is distributing and installing wholesale chiles throughout California.I am trying to achieve a Business Administration degree.  I am also learning sign language.
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
   
 






  




